version: "3.8"

services:
  voting-service:
    restart: "no"
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=vote-db
      - VOTE_DB_DB_NAME=vote-db
      - VOTE_DB_COLLECTION=votes
      - TOKEN_MANAGER_URL=http://token-manager
      - ROOT_PATH=/voting-service-api
      - KEYS_DB_HOST=vote-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys

  synchronization-service:
    restart: "no"
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=vote-db
      - VOTE_DB_DB_NAME=vote-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/synchronization-service-api

  voting-process-manager:
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ROOT_PATH=/voting-process-manager-api
      - KEYS_DB_HOST=vote-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys

  token-manager:
    restart: "no"
    environment:
      - TOKEN_DB_PORT=27017
      - TOKEN_DB_HOST=vote-db
      - TOKEN_DB_DB_NAME=vote-db
      - TOKEN_DB_COLLECTION=token
      - ROOT_PATH=/token-manager-api
      - ACCEPT_VALID_TOKEN=1

  admin-frontend:
    restart: "no"
