version: "3.8"

services:
  voting-service:
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=gateway-db
      - VOTE_DB_NAME=gateway-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/voting-service-api
      - TOKEN_MANAGER_URL=http://token-manager
      - KEYS_DB_HOST=gateway-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys

  synchronization-service:
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=gateway-db
      - VOTE_DB_NAME=gateway-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/synchronization-service-api

  voting-process-manager:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ROOT_PATH=/voting-process-manager-api
      - KEYS_DB_HOST=gateway-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys
      - TEST_INSERT_VT=True
      - TEST_INSERT_VT_IP=host.docker.internal:81

  token-manager:
    environment:
      - TOKEN_DB_PORT=27017
      - TOKEN_DB_HOST=gateway-db
      - TOKEN_DB_NAME=gateway-db
      - TOKEN_DB_COLLECTION=tokens
      - ROOT_PATH=/token-manager-api
      - ACCEPT_VALID_TOKEN=1

  statevector:
    environment:
      - ROOT_PATH=/statevector

  web:
    ports:
      - "8080:80"

  gateway-db:
    ports:
      - 8223:27017
    volumes:
      - ./gateway-db-data:/data/db

  admin-frontend:
      build:
        args:
          vite_base_path: /admin-frontend