version: "3.8"

services:
  voting-service:
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=vote-db
      - VOTE_DB_DB_NAME=vote-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/gateway/voting-service-api
      - TOKEN_MANAGER_URL=http://token-manager
      - KEYS_DB_HOST=vote-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys

  synchronization-service:
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=vote-db
      - VOTE_DB_DB_NAME=vote-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/gateway/synchronization-service-api

  voting-process-manager:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ROOT_PATH=/gateway/voting-process-manager-api
      - KEYS_DB_HOST=vote-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=keys-db
      - KEYS_DB_COLLECTION=keys
      - TEST_INSERT_VT=True
      - TEST_INSERT_VT_IP=host.docker.internal:8100

  token-manager:
    environment:
      - TOKEN_DB_PORT=27017
      - TOKEN_DB_HOST=vote-db
      - TOKEN_DB_DB_NAME=vote-db
      - TOKEN_DB_COLLECTION=tokens
      - ROOT_PATH=/gateway/token-manager-api
      - ACCEPT_VALID_TOKEN=1

  token-writer:
    build:
      context: ./dummy
      dockerfile: ./Dockerfile
    restart: "no"

  statevector:
    environment:
      - ROOT_PATH=/gateway/statevector

  web:
    ports:
      - "8101:80"

  vote-db:
    ports:
      - 8223:27017
    volumes:
      - /mnt/disk_2/docker_db_volumes/gateway-vote-db-data:/data/db
        
  admin-frontend:
      build:
        args:
          vite_base_path: /gateway/admin-frontend

