version: "3.8"

services:
  voting-service:
    build:
      context: ./voting-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - vote-db
  
  synchronization-service:
    build:
      context: ./synchronization-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - vote-db

  voting-process-manager:
    build:
      context: ./voting-process-manager
      dockerfile: ./Dockerfile
    restart: unless-stopped

  token-manager:
    build:
      context: ./token-manager
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - vote-db

  token-writer:
    build:
      context: ./token-writer
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - token-manager
    devices:
    - /dev/usb/bus:/dev/usb/bus
    privileged: true

  statevector:
    build:
      context: ./statevector
      dockerfile: ./Dockerfile
    restart: unless-stopped

  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    depends_on:
      - voting-process-manager
      - voting-service
      - synchronization-service
      - token-manager
      - vote-db
      - admin-frontend
      - statevector
    
  vote-db:
    image: mongo:4.4.13-rc0-focal
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
