version: "3.8"

services:
  voting-service:
    build:
      context: ./voting-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - gateway-db

  synchronization-service:
    build:
      context: ./synchronization-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - gateway-db

  voting-process-manager:
    build:
      context: ./voting-process-manager
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - statevector

  token-manager:
    build:
      context: ./token-manager
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - gateway-db

  token-writer:
    build:
      context: ./token-writer
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - token-manager
      - web
    devices:
    - /dev/bus/usb:/dev/bus/usb
    privileged: true

  statevector:
    build:
      context: ./statevector
      dockerfile: ./Dockerfile
    restart: unless-stopped

  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    depends_on:
      - voting-process-manager
      - voting-service
      - synchronization-service
      - token-manager
      - gateway-db
      - admin-frontend
      - statevector

  gateway-db:
    image: mongo:4.4.13-rc0-focal
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
