version: "3.8"

services:
  voting-service:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-voting-service
    restart: unless-stopped
    depends_on:
      - gateway-db
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=gateway-db
      - VOTE_DB_NAME=gateway-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/voting-service-api
      - TOKEN_MANAGER_URL=http://token-manager
      - KEYS_DB_HOST=gateway-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=gateway-db
      - KEYS_DB_COLLECTION=keys

  synchronization-service:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-synchronization-service
    restart: unless-stopped
    depends_on:
      - gateway-db
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=gateway-db
      - VOTE_DB_NAME=gateway-db
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/synchronization-service-api

  voting-process-manager:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-voting-process-manager
    restart: unless-stopped
    depends_on:
      - statevector
    environment:
      - ROOT_PATH=/voting-process-manager-api
      - KEYS_DB_HOST=gateway-db
      - KEYS_DB_PORT=27017
      - KEYS_DB_NAME=gateway-db
      - KEYS_DB_COLLECTION=keys
      - EVENTS_DB_NAME=gateway-db
      - EVENTS_DB_COLLECTION=events
      - TEST_INSERT_VT=True
      - TEST_INSERT_VT_IP=host.docker.internal:81

  token-manager:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-token-manager
    restart: unless-stopped
    depends_on:
      - gateway-db
    environment:
      - TOKEN_DB_PORT=27017
      - TOKEN_DB_HOST=gateway-db
      - TOKEN_DB_NAME=gateway-db
      - TOKEN_DB_COLLECTION=tokens
      - ROOT_PATH=/token-manager-api
      - ACCEPT_VALID_TOKEN=1

  token-writer:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-token-writer
    restart: unless-stopped
    depends_on:
      - token-manager
      - web
    devices:
    - /dev/bus/usb:/dev/bus/usb
    privileged: true
    environment:
      - TOKEN_MANAGER_PATH=token-manager
      - STATEVECTOR_PATH=web/statevector

  statevector:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-statevector
    restart: unless-stopped
    environment:
      - ROOT_PATH=/statevector

  web:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-web
    restart: unless-stopped
    depends_on:
      - voting-process-manager
      - voting-service
      - synchronization-service
      - token-manager
      - gateway-db
      - admin-frontend
      - statevector

  gateway-db:
    image: mongo:4.4.13-rc0-focal
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8223:27017
    volumes:
      - ../gateway-db-data:/data/db

  admin-frontend:
    image: team17-21.studenti.fiit.stuba.sk/electie-g-admin-frontend
    restart: unless-stopped
