version: "3.8"

services:
  synchronization-service:
    build:
      target: test
    restart: "no"

  voting-service:
    build:
      context: ./dummy
      dockerfile: ./Dockerfile
    restart: "no"

  admin-frontend:
    build:
      context: ./dummy
      dockerfile: ./Dockerfile
    restart: "no"

  voting-process-manager:
    build:
      context: ./dummy
      dockerfile: ./Dockerfile
    restart: "no"

  token-manager:
    build:
      context: ./dummy
      dockerfile: ./Dockerfile
    restart: "no"
