version: "3.8"

services:
  
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    container_name: tests
    # restart: unless-stopped
    depends_on:
      - vote-db-test
    # export useful environment variables to the service's container
    environment:
      - VOTE_DB_PORT=27017
      - VOTE_DB_HOST=vote-db-test
      - VOTE_DB_DB_NAME=vote-db-test
      - VOTE_DB_COLLECTION=votes
      - ROOT_PATH=/synchronization-service-api

  vote-db-test:
    # use existing mongo image from dockerhub
    image: mongo
    container_name: vote-db-test
    restart: unless-stopped
    ports:
      - 8223:27017
    # set user and group to mongo
    environment:
      - PUID=1000
      - PGID=1000

