version: "3.8"

services:
  statevector:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    restart: "no"
    environment:
      - ROOT_PATH=
      - SET_OFFICE_ID=42
      - SET_PIN=4242
      - SET_SERVER_ADDRESS=https://test.com
      - SET_SERVER_KEY=-----BEGIN PUBLIC KEY-----\ntest\n-----END PUBLIC KEY-----
