name: Gateway Stage

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  push:
    branches: [ development ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: Check out code
        uses: actions/checkout@v1

      - name: Checkout dev
        run: git checkout development

      - name: Checkout submodules
        run: git submodules init
        run: cd voting-service
        run: git checkout development
        run: git pull
        run: cd ..
        run: cd voting-process-manager
        run: git checkout development
        run: git pull
        run: cd ..
        run: cd synchronization-service
        run: git checkout development
        run: git pull
        run: cd ..

      - name: List
        run: ls -lah

      - name: Docker-Compose
        run: docker-compose -f docker-compose-stage.yml up -d --build
