name: Tests

on:
  pull_request:
    branches: [ main, development ]
    types: [ open ]

  push:

  workflow_dispatch:

jobs:
  test-synchronization-service:
    name: Test Synchronization Service
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: Check out code
        uses: actions/checkout@v2

      - name: Where/When am I in context of the GIT?
        run: git status

      - name: List
        run: ls -lah

      - name: Tests Docker-Compose
        run: docker-compose -f docker-compose.test.yml -f synchronization-service/docker-compose.test.yml -p gtest-sync up --build --exit-code-from synchronization-service --force-recreate --remove-orphans
  
  test-token-manager:
    name: Test Token Manager
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: Check out code
        uses: actions/checkout@v2

      - name: Where/When am I in context of the GIT?
        run: git status

      - name: List
        run: ls -lah

      - name: Tests Docker-Compose
        run: docker-compose -f docker-compose.test.yml -f token-manager/docker-compose.test.yml -p gtest-token up --build --exit-code-from token-manager --force-recreate --remove-orphans
